// English comments: read the form name from the URL
import { registerBuiltins } from '@vcl/registerVcl';

const params = new URLSearchParams(window.location.search);
const formName = params.get('form') ?? 'MainForm';

// English comments: declare all available form modules for Vite
const formModules = import.meta.glob('./forms/*/*.ts');

async function runForm(name: string): Promise<void> {
        const container = document.getElementById('app');

        if (!container) {
                throw new Error('Missing #app container');
        }

        // English comments: build the expected module path
        const modulePath = `./forms/${name}/${name}.ts`;

        // English comments: find the loader function generated by Vite
        const loader = formModules[modulePath];

        if (!loader) {
                container.innerHTML = `
            <h2>Form not found</h2>
            <p>Unable to load form "${name}"</p>
            <p>Expected module: ${modulePath}</p>
        `;
                console.error('Form module not found in Vite registry:', modulePath);
                console.log('Available form modules:', Object.keys(formModules));
                return;
        }

        try {
                const module = await loader();

                // English comments: assume the exported class has the same name as the form
                const FormClass = (module as Record<string, unknown>)[name] as
                        | {
                                  new (): { mount(container: HTMLElement): void };
                          }
                        | undefined;

                if (!FormClass) {
                        container.innerHTML = `
                <h2>Form class not found</h2>
                <p>Module loaded, but export "${name}" was not found.</p>
            `;
                        console.error(`Export "${name}" not found in module`, module);
                        return;
                }

                const form = new FormClass();
                form.mount(container);
        } catch (err) {
                console.error(err);
                container.innerHTML = `
            <h2>Error while loading form</h2>
            <p>Unable to run form "${name}"</p>
        `;
        }
}

void runForm(formName);
