/// <reference lib="dom" />
//import { installDelphineRuntime } from "./src/drt"; // <-- TS, pas .js
console.log('🔥 I AM ZAZAVUE – ENTRY EXECUTED')

console.log('I AM ZAZAVUE')

import { TForm, TColor, TApplication, TComponent, TButton, PluginRegistry, TPanel, TCompositeDCC, TMetaCompositeDCC } from '@vcl'
//import { TPluginHost } from '@drt/UIPlugin'
import { createHelloVuePlugin } from './createHelloVuePlugin'
import type { PropSpec } from '@vcl'

console.log('I AM ZAZAVUE')

// oxlint-disable-next-line no-debugger
debugger

//import type { DelphineServices } from '@drt/UIPlugin' // adaptez le chemin exact chez vous
//import { ComponentRegistry } from '@drt/ComponentRegistry';
//import { TPluginHost } from '@drt/UIPlugin';

//export function registerPluginTypes(reg: ComponentTypeRegistry): void {
/*
        // Example: any type name can be provided by a plugin.
        reg.register.registerType('chartjs-pie', (name: string, form: TForm, parent: TComponent) => {
                return new PluginHost(name, form, parent);
        });

        reg.registerType('vue-hello', (name: string, form: TForm, parent: TComponent) => {
                return new PluginHost(name, form, parent);
        });
        */
//}

class ZazaVue extends TForm {
        // Form components - This list is auto generated by Delphine
        // ---------------
        //button1 : TButton = new TButton("button1", this, this);
        //button2 : TButton = new TButton("button2", this, this);
        //button3 : TButton = new TButton("button3", this, this);
        // ---------------

        constructor(name: string) {
                super(name)
        }
        //import { installDelphineRuntime } from "./drt";

        /*
        const runtime = {
        handleClick({ element }: { element: Element }) {
        console.log("clicked!", element);
        //(element as HTMLElement).style.backgroundColor = "red";
        },
        };
        */

        protected onMyCreate(_ev: Event | null, _sender: TComponent) {
                //const btn = this.componentRegistry.get('button1')
                //if (btn) btn.color = TColor.rgb(0, 0, 255)
        }

        protected onMyShown(_ev: Event | null, _sender: TComponent) {
                //const btn = this.componentRegistry.get('buttonx')
                //if (btn) btn.color = TColor.rgb(0, 255, 255)
        }

        button1_onclick(_ev: Event | null, _sender: TComponent) {
                const btn = this.componentRegistry.get<TButton>('button1')
                if (!btn) {
                        console.warn('button1 not found in registry')
                        return
                }
                //btn.color = TColor.rgb(0, 0, 255);
                btn!.color = TColor.rgb(0, 0, 255)
                btn!.caption = 'MIMI'
                btn!.enabled = false
                console.log('Button1 clicked!!!!')
        }

        subButton1_onclick(_ev: Event | null, _sender: TComponent) {
                const panel = this.componentRegistry.get<TPanel>('myPanel')
                if (!panel) {
                        console.warn('myPanel not found in registry')
                        return
                }
                //btn.color = TColor.rgb(0, 0, 255);
                panel!.backgroundColor = TColor.rgb(54, 127, 173)
        }

        zaza_onclick(_ev: Event | null, _sender: TComponent) {
                const btn = this.componentRegistry.get<TButton>('buttonx')
                btn!.color = TColor.rgb(0, 255, 0)
                console.log('zazaVue clicked!!!!')
                //btn!.enabled = false;
        }

        //installDelphineRuntime(runtime);
} // class zazaVue

// -------------------------------------------------------- DCC --------------------------------------------------------

//type MyDCCProps = CompositeDCCProps & {
//caption?: string;
//enabled?: boolean;
//color?: TColor; // ou TColor, etc.
//}

class MyDCC extends TCompositeDCC {
        getMetaclass() {
                return TMetaMyDCC.metaclass
        }

        constructor(name: string, form: TForm, parent: TComponent) {
                super(name, form, parent)
        }
        _message: string = 'Salut tout le monde'
        get message() {
                return this._message
        }
        set message(v: string) {
                this._message = v
                console.log('Message prop updated:', v)
        }

        // protected get myprops(): MyDCCProps {
        //   return this.props as MyDCCProps
        // }
}

export class TMetaMyDCC extends TMetaCompositeDCC {
        static readonly metaclass: TMetaMyDCC = new TMetaMyDCC(TMetaCompositeDCC.metaclass, 'TMyDCC')

        protected constructor(superClass: TMetaCompositeDCC, name: string) {
                super(superClass, name)
                // et vous changez juste le nom :
        }
        getMetaclass(): TMetaMyDCC {
                return TMetaMyDCC.metaclass
        }

        create(name: string, form: TForm, parent: TComponent) {
                return new MyDCC(name, form, parent)
        }

        defProps(): PropSpec<MyDCC>[] {
                return [
                        //{ name: 'caption', kind: 'string', apply: (o, v) => (o.caption = String(v)) },
                        //{ name: 'enabled', kind: 'boolean', apply: (o, v) => (o.enabled = Boolean(v)) }
                        {
                                name: 'message',
                                kind: 'string',
                                retrieve: (o) => o._message,
                                apply: (o, v) => console.log('Applying message prop:', v),
                        },
                ]
        }
}

// ----------------------------------------------------- Application -----------------------------------------------------------------

class MyApplication extends TApplication {
        zazaVue: ZazaVue

        constructor() {
                super()
                this.zazaVue = new ZazaVue('zazaVue')
                this.mainForm = this.zazaVue

                // VueJS
                PluginRegistry.pluginRegistry.register('hello-vue', { factory: createHelloVuePlugin })
                //PluginRegistry.pluginRegistry.register('hello-vue2', { factory: createHelloVuePlugin2 })

                // DCC
                this.types.register(TMetaMyDCC.metaclass)
        }
        run() {
                //this.zaza.componentRegistry.buildComponentTree(this.zaza);
                //this.zaza.addEventListener('click');

                // au lancement
                this.runWhenDomReady(() => {
                        this.zazaVue.show()
                })
        }
} // class MyApplication

const myApplication: MyApplication = new MyApplication()
myApplication.run()
